project:
  type: website  
  output-dir: docs  # Cambia e directorio de salida de root a docs. En pages, github pages busca el sitio web en docs o en la raiz del repositorio.
 
website:
  title: "Machine Learning PP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
      - href: laboratorio1.qmd
        text: Laboratorio 1
      - href: clasification.qmd
        text: Clasificaciones        
      - href: midterm_clasificacin.qmd
        text: MidTerm Regresión
      - href: midterm_regresion.qmd
        text: MidTerm Clasificación
 
format:
  html:
    theme: sketchy
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
 