project:
  type: website  
  output-dir: docs  # Cambia e directorio de salida de root a docs. En pages, github pages busca el sitio web en docs o en la raiz del repositorio.
 
website:
  title: "Machine Learning PP"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - section: "Introduction to Machine Learning"
        contents:
          - altair.qmd
          - eda.qmd
      - section: "Clasificaction"
      - href: clasification.qmd
        contents:
          - categorical_encoding.qmd
          - categorical_pipeline.qmd
          - knn.qmd
      - section: "MidTerm"
        contents:
          - midterm_regresion.qmd
          - midterm_clasificacion.qmd
      - section: "Laboratories"
        contents:
          - laboratorio1.qmd
          - laboratorio2.qmd
      - section: "Natural Language Prceesing (NLP)"
        contents:
          - ml_text.qmd
          - bagofwords.qmd
          - tfidf.qmd
          - text_clasification.qmd
      - section: "Clustering"
        contents:
          - kmeans.qmd
          - hac.qmd
format:
  html:
    theme: sketchy
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
 