project:
  type: website
 
website:
  title: "Machine Learning PP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
 
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
 